/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Master;

import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level; 
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author COMPUTER
 */
public class Dokter extends javax.swing.JFrame {
    String sql;
    Koneksi kon;
    public Connection con;
    public Statement stt;
    public ResultSet rs;

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
        tabel.setModel(tblModel);
        this.setLocationRelativeTo(null);
        Tabel(tabel, new int[]{100,100,200,400,150});
        setDefaultTable();
        kode_dokter.setEnabled(false);
        kode_poli.setEnabled(false);
        nama_dokter.setEnabled(false);
        alamat.setEnabled(false);
        no_telp.setEnabled(false);
        tambah.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        keluar.setEnabled(true);
        batal.setEnabled(false);
        relasi();
        this.setSize(1070,750);//[1070, 779]

    }
    
    public void setDefaultTable(){
        String hubung = "jdbc:mysql://localhost:3306/poliklinik";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "Select * from Dokter";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
                data[0] = res.getString(1);
                data[1] = res.getString(2);
                data[2] = res.getString(3);
                
    data[3] = res.getString(4);
                data[4] = res.getString(5);
                tblModel.addRow(data);
            }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception exc) {
            System.err.println(exc.getMessage());
        }   
    } 

 String data[] = new String[5];
    
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb,int lebar[]) {
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int kolom = tb.getColumnCount();
        for(int i=0;i<kolom;i++) {
            javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(20);
        }
    }
    
    private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
                new String []{"Kode Dokter","Kode Poli","Nama Dokter","Alamat","No Telp"}
        ){
            boolean[] canEdit = new boolean []{
                false,false,false,false,false
            };
            public boolean isCellEditable(int rowIndex,int columnIndex){
                return canEdit[columnIndex];
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kode_dokter = new javax.swing.JTextField();
        nama_dokter = new javax.swing.JTextField();
        kode_poli = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        pencarian = new javax.swing.JTextField();
        cari = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Poli sehat.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Daftar Data Dokter");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel3.setText("DATA DOKTER");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inputkan Data Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel4.setText("Kode Dokter");

        jLabel5.setText("Kode Poli");

        jLabel6.setText("Nama Dokter");

        kode_poli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kode Poli" }));
        kode_poli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_poliActionPerformed(evt);
            }
        });

        jLabel7.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jLabel8.setText("No Telp");

        no_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_telpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kode_dokter)
                                        .addComponent(kode_poli, 0, 163, Short.MAX_VALUE)))
                                .addComponent(nama_dokter)
                                .addComponent(no_telp))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kode_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kode_poli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukan Kode Dokter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Detail Dokter");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Dokter", "Kode Poli", "Nama Dokter", "Alamat", "No Telphone"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/plus.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/save.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/delete.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/edit-user.png"))); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/13498058381938458744Back Button.svg.hi.png"))); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/unnamed.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ubah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(batal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tambah)
                .addComponent(simpan)
                .addComponent(hapus)
                .addComponent(ubah)
                .addComponent(batal)
                .addComponent(keluar))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Laporan Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/laporan.png"))); // NOI18N
        cetak.setText("Laporan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(368, 368, 368))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_telpActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String kd=kode_dokter.getText();
        String kp=kode_poli.getSelectedItem().toString();       
        String nd=nama_dokter.getText();
        String a=alamat.getText(); 
        String nt=no_telp.getText(); 
        if((kd.isEmpty())|(kp.isEmpty())|(nd.isEmpty())|(a.isEmpty())|(nt.isEmpty())){
            JOptionPane .showMessageDialog(null,"Masih Ada nilai yang kosong,silahkan dilengkapi!");
            nama_dokter.requestFocus();
        }
            else{
                Object[]options = {"YA","TIDAK"};
             int Konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menyimpan Data??","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
             
        if(Konfirmasi==JOptionPane.YES_OPTION){
        try {
            String hubung = "jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "insert into Dokter values('"+kode_dokter.getText()+"','"+kode_poli.getSelectedItem()+"','"+nama_dokter.getText()+"','"+alamat.getText()+"','"+no_telp.getText()+"')";
            stt.executeUpdate(SQL);
            data[0] = kode_dokter.getText();
            data[1] = kode_poli.getSelectedItem().toString();
            data[2] = nama_dokter.getText();
            data[3] = alamat.getText();
            data[4] = no_telp.getText();
            tblModel.insertRow(0, data);
            
            kode_dokter.setText("");
            kode_poli.setSelectedItem("");
            nama_dokter.setText("");
            alamat.setText("");
            no_telp.setText("");
            
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }

            kode_dokter.setEnabled(false);
            kode_poli.setEnabled(false);
            nama_dokter.setEnabled(false);
            alamat.setEnabled(false);
            no_telp.setEnabled(false);

            simpan.setEnabled(false);
            batal.setEnabled(true);
            ubah.setEnabled(false);
            hapus.setEnabled(false);
            tambah.setEnabled(true);
            keluar.setEnabled(true);
            }
        }

    }//GEN-LAST:event_simpanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        tabel_tampil();
        if(evt.getClickCount()==1){       //Tabel diklik 1 kali
            Tampil();
            int row = 0;
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        ubah();
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        batal();
        kode_poli.setSelectedItem(null);

    }//GEN-LAST:event_batalActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};
             int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Keluar?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            dispose();  
        }

    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try{
            String hubung ="jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            String cari = pencarian.getText();
            Statement stt = kon.createStatement();
            String sql ="Select * from Dokter where KodeDokter like '"+cari+"'";
            ResultSet rs= stt.executeQuery(sql);
            if(rs.next()){
                kode_dokter.setText(rs.getString(1));
                kode_poli.setSelectedItem(rs.getString(2));
                nama_dokter.setText(rs.getString(3));
                alamat.setText(rs.getString(4));
                no_telp.setText(rs.getString(5));
                kode_dokter.setEnabled(false);
                kode_poli.setEnabled(true);
                nama_dokter.setEnabled(true);
                alamat.setEnabled(true);
                no_telp.setEnabled(true);       
            }
            else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");           
            }
            stt.close();
            kon.close();            
        }
        catch(Exception e){
            System.out.println("ERROR."+e);}
        pencarian.setText("");
        tambah.setEnabled(false);
        simpan.setEnabled(false);
        ubah.setEnabled(true);
        batal.setEnabled(true);
        hapus.setEnabled(true);
        keluar.setEnabled(true);            

    }//GEN-LAST:event_cariActionPerformed

    private void kode_poliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_poliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_poliActionPerformed

    int row=0;
  
    public void Tampil(){  
        row = tabel.getSelectedRow();
        kode_dokter.setText(tblModel.getValueAt(row,0).toString());
        kode_poli.setSelectedItem(tblModel.getValueAt(row,1).toString());
        nama_dokter.setText(tblModel.getValueAt(row,2).toString());
        alamat.setText(tblModel.getValueAt(row,3).toString());
        no_telp.setText(tblModel.getValueAt(row, 4).toString());

        tambah.setEnabled(false);
        simpan.setEnabled(false);
        ubah.setEnabled(true);
        hapus.setEnabled(true);
        keluar.setEnabled(true);
        kode_dokter.setEnabled(true);
        kode_poli.setEnabled(true);
        nama_dokter.setEnabled(true);
        alamat.setEnabled(true);
        no_telp.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                try {
       UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");

        SwingUtilities.updateComponentTreeUI(new Dokter());
        } catch (Exception e){
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    public void tabel_tampil() {
            tambah.setEnabled(false);
            simpan.setEnabled(false);
            hapus.setEnabled(true);
            ubah.setEnabled(true);
            batal.setEnabled(true);
            kode_dokter.setEnabled(true);
            kode_poli.setEnabled(true);
            nama_dokter.setEnabled(true);
            alamat.setEnabled(true);
            no_telp.setEnabled(true);
    }
    
    public void tambah(){
        kode_dokter.setText("");
        kode_dokter.setEnabled(true);
        kode_poli.setSelectedItem("");
        kode_poli.setEnabled(true);
        nama_dokter.setText("");
        nama_dokter.setEnabled(true);
        alamat.setText("");
        alamat.setEnabled(true);
        no_telp.setText("");
        no_telp.setEnabled(true);
        tambah.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(true);
        ubah.setEnabled(false);
        keluar.setEnabled(true);
        batal.setEnabled(true);
        tabel.setEnabled(true);
        kode_dokter.requestFocus();
    }
    
    public void batal() {
            kode_dokter.setEnabled(false);
            kode_poli.setEnabled(false);
            nama_dokter.setEnabled(false);
            alamat.setEnabled(false);
            no_telp.setEnabled(false);      
            kode_dokter.setText("");
            kode_poli.setSelectedItem(null);  
            nama_dokter.setText("");
            alamat.setText("");
            no_telp.setText("");
            relasi();
            
            tambah.setEnabled(true);
            simpan.setEnabled(false);
            hapus.setEnabled(false);
            ubah.setEnabled(false);
            batal.setEnabled(false);
            keluar.setEnabled(true);
        }
    
 public void hapus(){
        Object[]options = {"YA","TIDAK"};
             int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Hapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
        try {
            String hubung = "jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "delete from Dokter where KodeDokter='"+kode_dokter.getText()+"'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            data[0] = kode_dokter.getText();
            data[1] = kode_poli.getSelectedItem().toString();
            data[2] = nama_dokter.getText();
            data[3] = alamat.getText();
            data[4] = no_telp.getText();
            
            kode_dokter.setText("");
            kode_poli.setSelectedItem("");
            nama_dokter.setText("");
            alamat.setText("");
            no_telp.setText("");         
            stt.close();
            kon.close();
        }catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
        kode_dokter.setText("");
        kode_poli.setSelectedItem("");
        nama_dokter.setText("");
        alamat.setText("");
        no_telp.setText("");
        kode_dokter.setEnabled(false);
        kode_poli.setEnabled(false);
        nama_dokter.setEnabled(false);
        alamat.setEnabled(false);
        no_telp.setEnabled(false);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        tambah.setEnabled(true);
        keluar.setEnabled(true);
        }
    }
    
    public void ubah(){
        String kd=kode_dokter.getText();
        String kp=kode_poli.getSelectedItem().toString();       
        String nd=nama_dokter.getText();
        String a=alamat.getText(); 
        String nt=no_telp.getText(); 
        if((kd.isEmpty())|(kp.isEmpty())|(nd.isEmpty())|(a.isEmpty())|(nt.isEmpty())){
            JOptionPane .showMessageDialog(null,"Masih Ada nilai yang kosong,silahkan dilengkapi!");
            nama_dokter.requestFocus();
        }
            else{
                Object[]options = {"YA","TIDAK"};
             int Konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Ubah Data??","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
             
        if(Konfirmasi==JOptionPane.YES_OPTION){
        try{
            String hubung = "jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "update Dokter set KodePoli = '"+kode_poli.getSelectedItem()+"',"+"NmDokter='"+nama_dokter.getText()+"',"+"AlmDokter='"+alamat.getText()+"',"+"TelpDokter='"+no_telp.getText()+"' where KodeDokter = '"+kode_dokter.getText()+"'";
            stt.executeUpdate(SQL);
            data[0] = kode_dokter.getText();
            data[1] = kode_poli.getSelectedItem().toString();
            data[2] = nama_dokter.getText();
            data[3] = alamat.getText();
            data[4] = no_telp.getText();
            tblModel.removeRow(row);
            tblModel.insertRow(row, data);
            
            kode_dokter.setText("");
            kode_poli.setSelectedItem("");
            nama_dokter.setText("");
            alamat.setText("");
            no_telp.setText("");
            simpan.setEnabled(false);
            
            stt.close();
            kon.close();
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
        kode_dokter.setText("");
        kode_poli.setSelectedItem("");
        nama_dokter.setText("");
        alamat.setText("");
        no_telp.setText("");
        kode_dokter.setEnabled(false);
        kode_poli.setEnabled(true);
        nama_dokter.setEnabled(true);
        alamat.setEnabled(true);
        no_telp.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(true);
       
        hapus.setEnabled(true);
        tambah.setEnabled(false);
        keluar.setEnabled(true);
        }
        }
    }
    
    private void relasi (){              //kode untuk mengambil data kode_poli dari tabel Poliklinik
        try{
            String hubung = "jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String sql = "select KodePoli from poliknik";
            ResultSet res = stt.executeQuery(sql);
            while (res.next()){
                kode_poli.addItem(res.getString(1));
            }
        }catch(Exception e){
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton batal;
    private javax.swing.JToggleButton cari;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kode_dokter;
    private javax.swing.JComboBox kode_poli;
    private javax.swing.JTextField nama_dokter;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
