/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Master;

import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JDialog;

import java.text.SimpleDateFormat;
/**
 *
 * @author COMPUTER
 */
public class Pegawai extends javax.swing.JFrame {
    String tanggal;
    /**
     * Creates new form Pegawai
     */
    public Pegawai() {
        initComponents();
        tabel.setModel(tblModel);
        Tabel(tabel, new int[]{100,180,200,300,150,150,100});
        setDefaultTable();

        nip.setEnabled(false);
        nama.setEnabled(false);
        alamat.setEnabled(false);
        telp.setEnabled(false);
        tgl_lahir.setEnabled(false);
        jenkel.setEnabled(false);
        tambah.setEnabled(true);
        simpan.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        keluar.setEnabled(true);
        batal.setEnabled(false);
        this.setSize(1070, 720);
        this.setLocationRelativeTo(null);
    }
    
    public void setDefaultTable(){
        String hubung = "jdbc:mysql://localhost:3306/poliklinik";
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "Select * from pegawai";
            ResultSet res = stt.executeQuery(SQL);
            while(res.next()) {
            data[0] = res.getString(1);
            data[1] = res.getString(2);
            data[2] = res.getString(3);
            data[3] = res.getString(4);
            data[4] = res.getString(5);
            data[5] = res.getString(6);
            tblModel.addRow(data);
        }
            res.close();
            stt.close();
            kon.close();
        }catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
 }
String data[] = new String[6];
private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
 private void Tabel(javax.swing.JTable tb,int lebar[]) {
 tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
 int kolom = tb.getColumnCount();
 for(int i=0;i<kolom;i++) {
 javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
 tbc.setPreferredWidth(lebar[i]);
 tb.setRowHeight(20);
 }
 }

 private javax.swing.table.DefaultTableModel getDefaultTabelModel() {
    return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String []{"NIP/NIK","Nama Pegawai","Alamat","No Telp","Tanggal Lahir","Jenis Kelamin"}
    ){
    boolean[] canEdit = new boolean []{
        false,false,false,false,false,false
    };
    public boolean isCellEditable(int rowIndex,int columnIndex){
        return canEdit[columnIndex];
        }
    };
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nip = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        telp = new javax.swing.JTextField();
        jenkel = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tgl_lahir = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        pencarian = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("NIP/NIK");

        jLabel2.setText("Nama Pegawai");

        jLabel3.setText("Alamat");

        jLabel4.setText("No Telp");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Jenis Kelamin");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        jenkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jenis Kelamin", "Laki-Laki", "Perempuan" }));

        jLabel7.setText("Inputkan Data Pegawai");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("DETAIL PEGAWAI");

        tgl_lahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_lahirPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jenkel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jenkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tgl_lahir.getAccessibleContext().setAccessibleParent(tgl_lahir);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Daftar Data Pegawai");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pegawai", "NIP/NIK", "Nama Pegawai", "Alamat", "No. Telp", "Tanggal Lahir", "Jenis Kelamin"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cari.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Masukan NIK/NIP Pegawai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tambah.png"))); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Simpan.png"))); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ubah.png"))); // NOI18N
        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Batal.png"))); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Keluar.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cetak.png"))); // NOI18N
        cetak.setText("Laporan");

        jLabel12.setText("Laporan Data");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel11.setText("Action");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMG-20201008-WA0006.jpg"))); // NOI18N
        jLabel13.setMaximumSize(new java.awt.Dimension(1170, 250));
        jLabel13.setMinimumSize(new java.awt.Dimension(1170, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(simpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(keluar)
                                .addGap(80, 80, 80)
                                .addComponent(cetak))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(485, 485, 485)
                                .addComponent(jLabel12)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 1170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(hapus)
                    .addComponent(ubah)
                    .addComponent(batal)
                    .addComponent(keluar)
                    .addComponent(cetak))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String np=nip.getText();
        String n=nama.getText();
        String a=alamat.getText();
        String t=telp.getText();
        String tl=tanggal;
        String jk=jenkel.getSelectedItem().toString();
        if((np.isEmpty())|(n.isEmpty())|(a.isEmpty())|(t.isEmpty())|(tl.isEmpty())|(jk.isEmpty())){
        JOptionPane .showMessageDialog(null,"Masih Ada nilai yang kosong,silahkan dilengkapi!");
        nip.requestFocus();
        }
        else{
            Object[]options = {"YA","TIDAK"};
            int Konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Menyimpan Data??","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);

        if(Konfirmasi==JOptionPane.YES_OPTION){
        }
        try {
            String hubung = "jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "insert into pegawai values('"+nip.getText()+"','"+nama.getText()+"','"+alamat.getText()+"','"+telp.getText()+"','"+tanggal+"','"+jenkel.getSelectedItem()+"')";
            stt.executeUpdate(SQL);
            data[0] = nip.getText();
            data[1] = nama.getText();
            data[2] = alamat.getText();
            data[3] = telp.getText();
            data[4] = tgl_lahir.getDate().toString();
            data[5] = jenkel.getSelectedItem().toString();
            tblModel.insertRow(0, data);
            nip.setText("");
            nama.setText("");
            alamat.setText("");
            telp.setText("");
            tgl_lahir.setDateFormatString("");
            jenkel.setSelectedItem("");
            stt.close();
            kon.close();
        }catch(Exception exc){
        System.err.println(exc.getMessage());
        }

        nip.setEnabled(false);
        nama.setEnabled(false);
        alamat.setEnabled(false);
        telp.setEnabled(false);
        tgl_lahir.setEnabled(false);
        jenkel.setEnabled(false);
        simpan.setEnabled(false);
        batal.setEnabled(false);
        ubah.setEnabled(false);
        hapus.setEnabled(false);
        tambah.setEnabled(true);
        keluar.setEnabled(true);
 }
    }//GEN-LAST:event_simpanActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_tambahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        tabel_tampil();
        if(evt.getClickCount()==1){
            Tampil();
            tambah.setEnabled(false);
            simpan.setEnabled(false);
            ubah.setEnabled(true);
            hapus.setEnabled(true);
            keluar.setEnabled(true);
            nip.setEnabled(true);
            nama.setEnabled(true);
            alamat.setEnabled(true);
            telp.setEnabled(true);
            tgl_lahir.setEnabled(true);
            jenkel.setEnabled(true);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        ubah();
    }//GEN-LAST:event_ubahActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        batal();
        jenkel.setSelectedItem(null);
    }//GEN-LAST:event_batalActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        Object[]options = {"YA","TIDAK"};
        int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin Keluar?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
        if(konfirmasi==JOptionPane.YES_OPTION){
            dispose();
        }

    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        try{
            String hubung ="jdbc:mysql://localhost:3306/poliklinik";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            String cari = pencarian.getText();
            Statement stt = kon.createStatement();
            String sql ="Select * from pegawai where nip like '"+cari+"'";
            ResultSet rs= stt.executeQuery(sql);
            if(rs.next()){
            nip.setText(rs.getString(1));
            nama.setText(rs.getString(2));
            alamat.setText(rs.getString(3));
            telp.setText(rs.getString(4));
            tgl_lahir.setDateFormatString(rs.getString(5));
            jenkel.setSelectedItem(rs.getString(6));

            nip.setEnabled(false);
            nama.setEnabled(true);
            alamat.setEnabled(true);
            telp.setEnabled(true);
            tgl_lahir.setEnabled(true);
            jenkel.setEnabled(true);
            }
            else{
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
            stt.close();
            kon.close();
            }
            catch(Exception e){
            System.out.println("ERROR."+e);}
            pencarian.setText("");
            tambah.setEnabled(false);
            simpan.setEnabled(false);
            ubah.setEnabled(true);
            hapus.setEnabled(true);
            keluar.setEnabled(true);
    }//GEN-LAST:event_cariActionPerformed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianActionPerformed

    private void tgl_lahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_lahirPropertyChange
        // TODO add your handling code here:
        if(tgl_lahir.getDate() != null){
            SimpleDateFormat Format = new SimpleDateFormat("yyyy-MM-dd");
            tanggal = Format.format(tgl_lahir.getDate());
        }
    }//GEN-LAST:event_tgl_lahirPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawai().setVisible(true);
            }
        });
    }

    int row = 0;
public void Tampil(){
 row = tabel.getSelectedRow();
 nip.setText(tblModel.getValueAt(row,0).toString());
 nama.setText(tblModel.getValueAt(row,1).toString());
 alamat.setText(tblModel.getValueAt(row,2).toString());
 telp.setText(tblModel.getValueAt(row, 3).toString());
 tgl_lahir.setToolTipText(tblModel.getValueAt(row, 4).toString());
 jenkel.setSelectedItem(tblModel.getValueAt(row, 5).toString());
}
public void tabel_tampil() {
 tambah.setEnabled(false);
 simpan.setEnabled(false);
 hapus.setEnabled(true);
 ubah.setEnabled(true);
 batal.setEnabled(true);
 nip.setEnabled(true);
 nama.setEnabled(true);
 alamat.setEnabled(true);
 telp.setEnabled(true);
 tgl_lahir.setEnabled(true);
 jenkel.setEnabled(true);

 }

 public void tambah(){
 nip.setText("");
 nip.setEnabled(true);
 nama.setText("");
 nama.setEnabled(true);
 alamat.setText("");
 alamat.setEnabled(true);
 telp.setText("");
 telp.setEnabled(true);
 tgl_lahir.setToolTipText("");
 tgl_lahir.setEnabled(true);
 jenkel.setSelectedItem("");
 jenkel.setEnabled(true);
 hapus.setEnabled(false);
 simpan.setEnabled(true);
 ubah.setEnabled(false);
 keluar.setEnabled(true);
 batal.setEnabled(true);
 tabel.setEnabled(true);
 nip.requestFocus();
 }

 public void batal() {
 nip.setEnabled(false);
 nama.setEnabled(false);
 alamat.setEnabled(false);
 telp.setEnabled(false);
 tgl_lahir.setEnabled(false);
 jenkel.setEnabled(false);
 nip.setText("");
 nama.setText("");
 alamat.setText("");
 telp.setText("");
 tgl_lahir.setDateFormatString("");
 jenkel.setSelectedItem("");

 tambah.setEnabled(true);
 simpan.setEnabled(false);
 hapus.setEnabled(false);
 ubah.setEnabled(false);
 batal.setEnabled(false);
 }

 public void hapus(){
 Object[]options = {"YA","TIDAK"};
 int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Ingin Hapus Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
 if(konfirmasi==JOptionPane.YES_OPTION){
 }
 try {
 String hubung = "jdbc:mysql://localhost:3306/poliklinik";
 Class.forName("com.mysql.jdbc.Driver").newInstance();
 Connection kon = DriverManager.getConnection(hubung,"root","");
 Statement stt = kon.createStatement();
 String SQL = "delete from pegawai where nip='"+nip.getText()+"'";
 stt.executeUpdate(SQL);
 tblModel.removeRow(row);
 data[0] = nip.getText();
 data[1] = nama.getText();
 data[2] = alamat.getText();
 data[3] = telp.getText();
 data[4] = tanggal;
 data[5] = jenkel.getSelectedItem().toString();
 nip.setText("");
 nama.setText("");
 alamat.setText("");
 telp.setText("");
 tgl_lahir.setToolTipText("");
 jenkel.setSelectedItem("");

 stt.close();
 kon.close();
 }catch(Exception exc) {
 System.err.println(exc.getMessage());
 }
 nip.setText("");
 nama.setText("");
 alamat.setText("");
 telp.setText("");
 tgl_lahir.setToolTipText("");
 jenkel.setSelectedItem("");
 nip.setEnabled(false);
 nama.setEnabled(false);
 alamat.setEnabled(false);
 telp.setEnabled(false);
 tgl_lahir.setEnabled(false);
 jenkel.setEnabled(false);
 simpan.setEnabled(false);
 ubah.setEnabled(false);
 hapus.setEnabled(false);
 tambah.setEnabled(true);
 keluar.setEnabled(true);
 }

 public void ubah(){
 Object[]options = {"YA","TIDAK"};
 int konfirmasi=JOptionPane.showOptionDialog(null,"Apakah Anda Ingin Ubah Data?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
 if(konfirmasi==JOptionPane.YES_OPTION){
 }
 try{
 String hubung = "jdbc:mysql://localhost:3306/poliklinik";
 Class.forName("com.mysql.jdbc.Driver").newInstance();
 Connection kon = DriverManager.getConnection(hubung,"root","");
 Statement stt = kon.createStatement();
 String SQL = "update pegawai set nip ='"+nip.getText()+"',"+"nama='"+nama.getText()+"',"+"alamat='"+alamat.getText()+"',"+"telp='"+telp.getText()+"',"+"tgl_lahir='"+tanggal+"',"+"jenkel='"+jenkel.getSelectedItem()+"' where nip = '"+nip.getText()+"'";

stt.executeUpdate(SQL);
 data[0] = nip.getText();
 data[1] = nama.getText();
 data[2] = alamat.getText();
 data[3] = telp.getText();
 data[4] = tanggal;
 data[5] = jenkel.getSelectedItem().toString();
 tblModel.removeRow(row);
 tblModel.insertRow(row, data);
 nip.setText("");
 nama.setText("");
 alamat.setText("");
 telp.setText("");
 tgl_lahir.setToolTipText("");
 jenkel.setSelectedItem("");
 simpan.setEnabled(false);

 stt.close();
 kon.close();
 }catch(Exception exc){
 System.err.println(exc.getMessage());
 }
 nip.setText("");
 nama.setText("");
 alamat.setText("");
 telp.setText("");
 tgl_lahir.setToolTipText("");
 jenkel.setSelectedItem("");
 nip.setEnabled(false);
 nama.setEnabled(false);
 alamat.setEnabled(false);
 telp.setEnabled(false);
 tgl_lahir.setEnabled(false);
 jenkel.setEnabled(false);
 simpan.setEnabled(false);
 ubah.setEnabled(false);
 hapus.setEnabled(false);
 tambah.setEnabled(true);
 keluar.setEnabled(true);
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jenkel;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nip;
    private javax.swing.JTextField pencarian;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField telp;
    private com.toedter.calendar.JDateChooser tgl_lahir;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
